// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Summarizes the key differences between two JSON responses.
 *
 * - summarizeDifferences - A function that summarizes the differences between two JSON responses.
 * - SummarizeDifferencesInput - The input type for the summarizeDifferences function.
 * - SummarizeDifferencesOutput - The return type for the summarizeDifferences function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const SummarizeDifferencesInputSchema = z.object({
  response1: z.any().describe('The first JSON response.'),
  response2: z.any().describe('The second JSON response.'),
});
export type SummarizeDifferencesInput = z.infer<typeof SummarizeDifferencesInputSchema>;

const SummarizeDifferencesOutputSchema = z.object({
  summary: z.string().describe('A concise summary of the key differences between the two JSON responses.'),
});
export type SummarizeDifferencesOutput = z.infer<typeof SummarizeDifferencesOutputSchema>;

export async function summarizeDifferences(input: SummarizeDifferencesInput): Promise<SummarizeDifferencesOutput> {
  return summarizeDifferencesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'summarizeDifferencesPrompt',
  input: {
    schema: z.object({
      response1: z.any().describe('The first JSON response.'),
      response2: z.any().describe('The second JSON response.'),
    }),
  },
  output: {
    schema: z.object({
      summary: z.string().describe('A concise summary of the key differences between the two JSON responses.'),
    }),
  },
  prompt: `You are an AI expert in comparing JSON responses and identifying key differences.

You will receive two JSON responses, and your task is to summarize the key differences between them in a concise, human-readable format. Focus on the most important changes and provide a summary that allows a user to quickly understand the significant differences without manually comparing the entire JSON structure.

Response 1: {{{response1}}}
Response 2: {{{response2}}}`,
});

const summarizeDifferencesFlow = ai.defineFlow<
  typeof SummarizeDifferencesInputSchema,
  typeof SummarizeDifferencesOutputSchema
>({
  name: 'summarizeDifferencesFlow',
  inputSchema: SummarizeDifferencesInputSchema,
  outputSchema: SummarizeDifferencesOutputSchema,
}, async input => {
  const {output} = await prompt(input);
  return output!;
});

